### ISSUE TITLE
Major content addition to Telos 1K Plus Magic

### ISSUE THREAD

**Issue by Pernix4** [pvme/pvme-guides#1342]
**__Phase 1__**
⬥ P1 lure guide
⬥ Back up rotation if you fail the TC
⬥ Mention of pre-SoL for pushing enrage.

**__Phase 4__**
⬥ That fast drop option should be used p4 if p3 ends ideally since asphyx is on cooldown.
⬥ How to fast entangle P4 Font 3.

**__Phase 5__**
⬥ What to do if volcanics hit you early p5.
That fast drop option should be used p4 if p3 ends ideally since asphyx is on cooldown,
⬥ Ideal Phase 5 venges
⬥ Explain how Tsunami works.
⬥ Entangle immune golems.
⬥ How to Entangle
⬥ Volcanics have Scythe range.
⬥ Why it's important to stun in back beam.
⬥ Movement on tick
⬥ Stunning after Surge
⬥ How to lure back beam.
⬥ How to clear side beam viruses
⬥ How to get golems in a single file for back beam.

**Comment by inferiumRS3** [comment]
@Pernix4  think we can close this given the current fsoa channel + non-fsoa channel?
