### ISSUE TITLE
Revamp #vorago completely

### ISSUE THREAD

**Issue by Pernix4** [pvme/pvme-guides#1358]
Transform it into a more mechanics based explanation channel, but also mention the minor differences between trio and duo (e.g., p2 bleed clears), and also mention things like how to lure scops, lure p1, etc

ideally someone can read this channel, go in without any real rotation, and probably still get kills if they know how to properly deal with mechanics and other info listed in this channel etc

⬥ Attack order
⬥ Explaining mechanics and how to deal with them, aswell as worst case scenarios (3ts p3 etc)
⬥ Attack speed
⬥ Brief explanation of how p5 works and what causes pushback against you
⬥ Brief explanation of natty timings, and also how to md your ult as non-melee
⬥ How to clear bleeds p2, and how to force red
⬥ How to position yourself for base spot, and better base spot
⬥ How to lure p1, how to lure p1 as melee
⬥ How to climb, list several climb strats probably
⬥ Natty timings and how to ensure you md on p5 for non-melee
⬥ Base spot

**Comment by aOs-SerasLove** [comment]
think closing this is ok kermitdetective
