### ISSUE TITLE
Add to #mechanics

### ISSUE THREAD

**Issue by Pernix4** [pvme/pvme-guides#1377]
• Flanking tech(solo/immobile)
• Losing your target/dropping combat
• Surge/Bd tech(cutting corners/during gcd)
• Prebarging
• On cast vs on hit(ults, ss, etc) 
    • Can be expanded though
• Pre-phasing/Adren dumping
• Max hp boosting tech(if its not already somewhere else)

**Comment by Toosday** [comment]
added to scope of https://github.com/pvme/pvme-guides/issues/3490
