### ISSUE TITLE
#dpm-advice-faq: styling fixes + add note to the cancelling video

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1563]
To do:
1) Make the cancelling video url its own link and remove the bolding: https://discord.com/channels/534508796639182860/622623001694699560/850889029317689354
2) Add a note saying the buff bar timers shown are outdated in the video, and mention to use !cancelling in #bot-commands instead to get up-to-date timers
3) Remove the bolding of the spreadsheet link under the "Ability prioritisation in your rotation" subheader: https://discord.com/channels/534508796639182860/622623001694699560/850889108686766110
Issue Level: Easy
Leave a comment to notify you have claimed the issue

**Comment by HolyDoggie** [comment]
did it
