### ISSUE TITLE
#ed1-ranged: "This rotation requires the :heightenedsenses: Heightened senses relic. At the start camp :RubyBakri: and swap to :HydrixBakri: for 2 abilities after Ruby proc." is mentioned twice, remove it once

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1564]
Message Link: https://discord.com/channels/534508796639182860/798986473646325770/859824297043034153
Issue Level: Easy
Leave a comment to notify you have claimed the issue

**Comment by hoobsie** [comment]
Fixed
