### ISSUE TITLE
More Solak Preset Stuff

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1608]
#solak-mechanics:
Learner Mage Brid Preset: Change 4 pouch setup to 3 pouch (blue orange red), assumes BP smoke cloud (this will give no veng)
Then, add t92 spear

Learner Range Brid Preset: Change the 3 pouch non-melee pouch setup to the 2 pouch non-melee (BP Smoke Cloud) setup
Then, add t92 spear

All Solak Rot channels (mage brid, range camp, range brid) add a note/bullet to general notes section about BP Smoke Cloud, also in brid channels mention the off-style body (presumably means the non-melee body (check with lies and tears to confirm if uncertain) also acts as mobile switch, and the malev helm is there for bigger veng

Issue Level: Easy
Leave a comment to notify you have claimed an issue

**Comment by toenailrs** [comment]
Hi zeroken, Toenail here. 
As a learner to solak Range/Melee brid (I'm used to mage/melee) I feel this setup I'm going to post is sufficient for a learner brid setup. 
Take out a brew/spiritual for a t92 spear. Spear is nice but for dps afaik its not as important as it is for base.
pouches are based on PVME setup.
https://i.imgur.com/M31GLB3.png @Archken

**Comment by Archken** [comment]
done
