### ISSUE TITLE
telos channels: Add a note about how important doing the defensive > wait 2ticks > surge abil > tc abil is at telos to flinch him, along with video comparing that start vs a normal start to show how telos autos at different times and makes/breaks the p1 rotation

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1667]
Issue Level: Easy
Leave a comment to notify you have claimed the issue.

**Comment by BrandonTiltos** [comment]
done for mage 0-999 and non fsoa. should be mentioned might be worth replacing the tc video above the mechanics section in 0-999, but for now i just left it.
