### ISSUE TITLE
#dpm-advice-mage, abil info additions and changes

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1735]
~- Add Kerapac gloves to combust + db~
    ~- Tl;dr of kerapac interactions: https://discord.com/channels/534508796639182860/536062588090318850/871298098431918120
Basically, combust has to hit in <10t from db cast to get the effect (therefore combust has to hit t0-t9), so combust has to be cast during t0-t7 if its being cast after db where db is t0~
- Add drider to db
~- Add gconc~
~- add soa spec~
~- mention adren cost of gstaff (should be first bullet)~
    ~- delete the "Cooldown: based on a couple factors" and instead add "*Note: All Special Attacks have an inherent cooldown when doing back-to-back special attacks, this is discussed in <#689212192398114875>*" under the "Special Attacks" header~
~- add "⬥ To see the damages of the listed things with your gear set up, feel free to make a copy of the following sheet to customize: <https://docs.google.com/spreadsheets/u/2/d/1F5vBijBmZw2aWI-OA0DxV0Iw5efolCx58nqkzGLeqC0> ​" under the general header as a 3rd bullet~

Issue Level: Easy
Leave a comment to notify you have claimed the issue

**Comment by Archken** [comment]
did some of the listed changes in the issue, crossed out what i did, the uncrossed things (adding drider to db + soa spec being included in abil info) still needs to be done

**Comment by Archken** [comment]
infernum has handled adding FSOA spec to channel

**Comment by inferiumRS3** [comment]
Looks like all major items have been handled.
