### ISSUE TITLE
Bringing #dpm-advice-mage further up-to-date with Kerapac additions

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1780]
1) Add Kerapac gloves to switches section (add after flank)
~2) Updating ability priority and building a rotation section (including updating the image sheet itself) to account for gconc, wrack and ruin, exsang, etc~
~3) Updating general sun rot section to account for gconc etc (alternatively adding full example sun rots which would be better)~
Related issues:
https://github.com/pvme/pvme-guides/issues/1735
~https://github.com/pvme/pvme-guides/issues/1639~

**Comment by Archken** [comment]
Inferium did 2) and 3). Since only 1) is left downgrading to an easy issue

**Comment by inferiumRS3** [comment]
last 1) https://github.com/pvme/pvme-guides/pull/2343
