### ISSUE TITLE
#pvm-spreadsheet: shift all relevant sheets from #ability-damage-maths to it then archive the channel

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1817]
Relevant sheets should be <https://docs.google.com/spreadsheets/d/1OetEUz4xU5sg7pqmJBkkafmZIye8qoPOXprUPGhin14/edit?usp=sharing> and <https://docs.google.com/spreadsheets/d/1F5vBijBmZw2aWI-OA0DxV0Iw5efolCx58nqkzGLeqC0/>

Issue Level: Easy
Leave a comment to notify you have claimed the issue

**Comment by hellslionrs** [comment]
done
