### ISSUE TITLE
#king-black-dragon, #corporeal-beast (afk preset), all gwd2 channels' afk presets: add potion resevoir to preset notes + explain briefly what it does 

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#1824]
Issue Level: Easy
Leave a comment to notify you have claimed the issue

**Comment by ThePraesul** [comment]
Think I've fully taken care of this; no Scrimshaw corp still lacks it in the pic so I've left that off, and I'm not entirely happy with the formatting of where I've put it in Corp because it makes it sound more important than it is.
