### ISSUE TITLE
![style]perks command for each style (either make a set for both advanced and entry, or if possible make it 1 command/style for both if can make look nice) (use embed/single image)

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#2113]

**Comment by inferiumRS3** [comment]
here are two samples ive come up with, first is with all, second is just starter:
[perkCommand.txt](https://github.com/pvme/pvme-guides/files/8240702/perkCommand.txt)
[testStarterArmour.txt](https://github.com/pvme/pvme-guides/files/8240703/testStarterArmour.txt)

**Comment by Archken** [comment]
gonna close this because it has more issues than i had thought
