### ISSUE TITLE
#aod rot channels: explain what 1/3 2/4 etc means somewhere within the channel (or in the main channel)

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#2554]

**Comment by Ferroric** [comment]
https://ptb.discord.com/channels/534508796639182860/897299150742356039/971300510340644875 Is mentioned in #aod-ranged channel as linked.  Should be a resolved issue?

**Comment by inferiumRS3** [comment]
@Ferroric I'd recommend just repeating the information where it is needed in each channel rather than linking
