### ISSUE TITLE
Add example hour VODs for Telos

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2610]
G0att has magic and ranged but not melee.

**Comment by inferiumRS3** [comment]
FSOA mage added: https://github.com/pvme/pvme-guides/pull/2734

**Comment by blockdudePvmeGithub** [comment]
Zach the greg slayer has been doing lots of melee telos. We could see if he has an hour vod saved somewhere (or is willing to record one).

**Comment by Ferroric** [comment]
Asked Ralph for a melee telos hour, will check back in soon tm*

**Comment by Ferroric** [comment]
Melee added in #3161
