### ISSUE TITLE
Move all spreadsheets out of miscellaneous-information into new category “spreadsheets”

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2617]
![71A5E64B-C64D-4089-828F-EAC0680E57F6](https://user-images.githubusercontent.com/94665678/158713049-025e5742-e969-43eb-b342-28d1737d7429.jpeg)
![E16E870E-68AA-4F0D-9A28-D87E9555EE49](https://user-images.githubusercontent.com/94665678/158713053-22bcab54-ebc7-4062-916b-f4e59650bb87.jpeg)

**Comment by Ferroric** [comment]
Should be resolved in #2835
