### ISSUE TITLE
Fix small typos in #dpm-advice-mage

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2641]
Small typos, 2x "sushine" in https://github.com/pvme/pvme-guides/blob/master/dpm-advice/dpm-advice-mage.txt

![image](https://user-images.githubusercontent.com/94665678/159604620-df3cbffb-9f63-4020-82c2-25d07f1dee4a.png)

**Comment by blockdudePvmeGithub** [comment]
https://github.com/pvme/pvme-guides/issues/2641
