### ISSUE TITLE
Update !banking command preset to include cryptbloom

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2642]
Update the preset using preset generator (link: [here](https://docs.google.com/spreadsheets/d/1WpbEGSWK5qhsdq7ERMYh70PUOg9BTW85nFW0TAcNWCQ/edit?usp=sharing)) to use cryptbloom instead of Achto.

File: https://github.com/pvme/pvme-guides/blob/master/commands/banking.txt

**Comment by Whim-Btw** [comment]
am fixing

**Comment by Whim-Btw** [comment]
Awaiting 2 pictures on rotation builder

**Comment by Whim-Btw** [comment]
done
