### ISSUE TITLE
Clean up GWD2 AFK

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2643]
Standardize how we organize our GWD2 channels, and make sure each one has Frank's magic AFK methods linked to it. Currently Greg is missing this.

There's also a lot of fluff that could be trimmed out/cleaned up. Thread for more info: https://discord.com/channels/534508796639182860/537042924026724353/955464627112804372

Files:
https://github.com/pvme/pvme-guides/blob/master/mid-tier-pvm/gregorovic.txt
https://github.com/pvme/pvme-guides/blob/master/mid-tier-pvm/helwyr.txt
https://github.com/pvme/pvme-guides/blob/master/mid-tier-pvm/vindicta.txt
https://github.com/pvme/pvme-guides/blob/master/mid-tier-pvm/twin-furies.txt

**Comment by hellslionrs** [comment]
on it

**Comment by Ferroric** [comment]
![image](https://user-images.githubusercontent.com/104602266/170157269-514191ff-72e8-4eac-95aa-bc88047cccc3.png)
Adding this here if it is worth anything.

**Comment by Ferroric** [comment]
This is done now
