### ISSUE TITLE
Small typo in !smokecloud command

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2647]
`->` should become `→`

![Screenshot 2022-03-22 214924](https://user-images.githubusercontent.com/94665678/159606847-ac9d2b9b-9148-437c-abbd-1ed3bc8c8b6d.png)

File: https://github.com/pvme/pvme-guides/blob/master/commands/smokecloud.txt

**Comment by EddieCornelious** [comment]
#2651
