### ISSUE TITLE
Update melee preset in #solak-basic to include Abyssal Scourge

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2648]
Replace Leng MH with Scourge, using preset generator ([link here](https://docs.google.com/spreadsheets/d/1WpbEGSWK5qhsdq7ERMYh70PUOg9BTW85nFW0TAcNWCQ/edit?usp=sharing))

![image](https://user-images.githubusercontent.com/94665678/159607345-a5305d32-95ce-403c-bd19-ec8d6a833c62.png)

**Comment by Whim-Btw** [comment]
done in https://github.com/pvme/pvme-guides/pull/2765
