### ISSUE TITLE
Standardize "PvME" capitalization

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2697]
![image](https://user-images.githubusercontent.com/94665678/161448907-1f98311f-3cef-4f67-85ef-7ce6b9fb29f4.png)

Ry can do mass find/replaces - can get his help with this.

**Comment by blockdudePvmeGithub** [comment]
https://github.com/pvme/pvme-guides/pull/2894

**Comment by txj-xyz** [comment]
This can be closed
