### ISSUE TITLE
Fix dead link in #nex-solo-ranged-ecb 

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2698]
File: https://github.com/pvme/pvme-guides/blob/master/nex-aod/nex-solo-ranged-ecb.txt

![image](https://user-images.githubusercontent.com/94665678/161448936-4b713cee-21b7-4415-9b1a-af431b86f176.png)

**Comment by txj-xyz** [comment]
Looking into this, applied fix already, awaiting merge of #2763 first

**Comment by hoobsie** [comment]
Fixed
