### ISSUE TITLE
Categorize + Clean up !pvmehelp command

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2704]
File: https://github.com/pvme/pvme-guides/blob/master/commands/pvmehelp.txt

![image](https://user-images.githubusercontent.com/94665678/161449132-fa2b9b2c-6600-4e2d-8c45-525482b7731f.png)

**Comment by Archken** [comment]
i'll look into this because i need an excuse to not do anything

**Comment by Archken** [comment]
track finished this
