### ISSUE TITLE
Add link to abbreviations in #how-to-read-pvme

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2705]
File: https://github.com/pvme/pvme-guides/blob/master/information/how-to.txt

Link to abbrevations: https://docs.google.com/document/d/1yZmDhx-SJsrVo0iTNwgMN3YsuJ9CrHcySd3hptvz3Ds

![image](https://user-images.githubusercontent.com/94665678/161449189-fc64130b-e4e8-49b5-862d-485f5eee1ef8.png)

**Comment by Ezeei** [comment]
Done as part of #2761
