### ISSUE TITLE
Add link to new "basic ability priority order" spreadsheet

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2714]
Link to spreadsheet: https://docs.google.com/document/d/1qfp33_-YUh_SOtD8NjchcjY6sL9_HeYH-ZpJrMqIb5M/edit?usp=sharing

Probably a link in pvm-spreadsheets, and then reference it in dpm-advice-general/faq? Feel free to suggest another place.

**Comment by txj-xyz** [comment]
Spoke we Inferium, Will keep the guide separate from the old sheet until we can update it.


See:  #2758 for changes and details

**Comment by inferiumRS3** [comment]
https://github.com/pvme/pvme-guides/pull/2758
