### ISSUE TITLE
!ruby command: basically explains when and how to use ruby (and how you would weave in other (hydrix) bolts

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#2807]
![image](https://user-images.githubusercontent.com/77247574/166223150-1686b5d2-f465-4fde-a30c-e6b2b3c94ca2.png)

**Comment by txj-xyz** [comment]
Creating this.

**Comment by txj-xyz** [comment]
This is my first time writing any sort of "guide" so please bear with me as I'd like to be better at this :)

How does this look for a rough draft?

![](https://cdn.discordapp.com/attachments/918670717753630822/971527784423899156/T7tck6gndobUsSHVdg3t.png)

**Comment by txj-xyz** [comment]
#2840
