### ISSUE TITLE
Add explicit colour names to !eof command

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2848]
![image](https://user-images.githubusercontent.com/94665678/167229020-3a45ca76-77a9-4f99-acba-f83fb3e9ced5.png)

File: https://github.com/pvme/pvme-guides/blob/master/commands/eofs.txt

Original image was from #armour-and-weapons channel

**Comment by Ferroric** [comment]
https://ptb.discord.com/channels/534508796639182860/689575078698287152/972338301585477682 looks ugly but will send it tomorrow if no alterations are needed

**Comment by Ferroric** [comment]
Completed
