### ISSUE TITLE
Update #armour-and-weapons spirit shield damage to consider Hellhound

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2850]
![image](https://user-images.githubusercontent.com/94665678/167229179-3d9adc35-f00d-49e2-8019-901bf5260f03.png)

File: https://github.com/pvme/pvme-guides/blob/master/upgrading-info/armour-and-weapons.txt

**Comment by Ferroric** [comment]
Completed in #2870
