### ISSUE TITLE
Investigate if updated version exists, then add world list image somewhere

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2854]
![image](https://user-images.githubusercontent.com/94665678/167229619-24833ace-635a-43c3-a126-00c2183a86fa.png)

Not sure where this best fits. Feel free to suggest.

Pernix may know how to find an updated version.

**Comment by txj-xyz** [comment]
I have a list ready of all worlds, however it's a bit difficult to build out the list in a region manner.

I can cross compare the list one by one.

I'll aim to finish this perhaps this week.
