### ISSUE TITLE
Create !records command to link to PVM Records site/server

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2857]
Create a new command to link to pvm records affiliate server / website.

Don't forget to also update #how-to-use-pvme and !pvmehelp command:
https://github.com/pvme/pvme-guides/blob/master/information/how-to.txt
https://github.com/pvme/pvme-guides/blob/master/commands/pvmehelp.txt

Website: https://www.pvm-records.com/
Discord link: https://discord.gg/AR5qErBGDs

**Comment by Ferroric** [comment]
Completed
