### ISSUE TITLE
Add links to new header art for Chaos Elemental + GWD1 Bosses

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2879]
Chaos Elemental   `https://i.imgur.com/LcvLEL0.jpg`
Zilyana           `https://i.imgur.com/wYEMNqk.jpg`
Graardor          `https://i.imgur.com/00g3QsG.jpg`
Kree              `https://i.imgur.com/uIveHlv.jpg`
K'ril             `https://i.imgur.com/LmjPPpL.jpg`

**Comment by txj-xyz** [comment]
See #2880
