### ISSUE TITLE
Add links to new header art (AoD, Har-Aken, Jad, KQ, KBD)

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2904]
AoD:               `https://i.imgur.com/zX4OYA6.jpg`
Har-Aken:          `https://i.imgur.com/MwifwHe.jpg`
Jad:               `https://i.imgur.com/cibB2kx.jpg`
Kalphite Queen:    `https://i.imgur.com/B4KkbaD.jpg`
King Black Dragon: `https://i.imgur.com/6CksiEj.jpg`

**Comment by Ezeei** [comment]
on it

**Comment by Ezeei** [comment]
done in #2905
