### ISSUE TITLE
Make Frank tackle Frank's to do list

### ISSUE THREAD

**Issue by friggity** [pvme/pvme-guides#2941]
Paying more attention to issues tab but here's what I have left assigned to myself, aiming to complete throughout the next week as I have time:

- [x] Update poison section in mechanics with Bik arrows, new poisoning hit types (just Abyssal Parasites I think), link Big Archives wiki calculator and maybe give poison dpm scenarios 
- [x] Add Scourge setup to Gregorovic AFK
- [x] Add Scourge setup to Vindicta AFK
- [x] Add Scourge setup to Helwyr AFK
- [x] Add Scourge + salamancy setup to Rathis AFK section

**Comment by Ferroric** [comment]
Has since been completed
