### ISSUE TITLE
Investigate gp/kill for HM Kerapac

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#2978]
![image](https://user-images.githubusercontent.com/104602266/170150415-b881b371-c0f0-4e40-90d3-b1888646d323.png)

(Requires sheet access I think)

**Comment by F1shBones** [comment]
It is indeed wrong. The current Commons GP/kill for HM Kerapac is the value of 1 pile. The correct value is 3x what is currently displayed.

**Comment by hoobsie** [comment]
fixed
