### ISSUE TITLE
Add info on inconsistent weapon tier to damage tier

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#2980]
![image](https://user-images.githubusercontent.com/104602266/170152165-8d1a8d53-7484-4a8a-b409-41c68198375f.png)
Also T85 glac is T88 dmg.  May need investigating other similar weapons.  Unsure where this information would fit in.

**Comment by Archken** [comment]
this was in relation to !weapon, the change was made a while back. Guess I forgot to check that instance of it, my bad
