### ISSUE TITLE
Update Rex Matriarchs afk presets

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#2984]
![image](https://user-images.githubusercontent.com/104602266/170154122-3e6dd9f7-c71c-4666-99fa-e56f40c46601.png)
Might be something for Frank to look at (no pressure).

**Comment by Ferroric** [comment]
![image](https://user-images.githubusercontent.com/104602266/170157544-a9c9a3ca-3113-41e3-966b-6767ed7f6359.png)
Just use this actually

**Comment by Uta1105** [comment]
Melee preset was updated to include
- zuk cape
- amulet of salamancy
- Wen book
