### ISSUE TITLE
Command for non pf sunshine/swiftness 

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#2995]
![image](https://user-images.githubusercontent.com/104602266/170159569-1918ffa0-b76e-472d-a0ef-2c06cef680b7.png)

**Comment by blockdudePvmeGithub** [comment]
Is this really needed?

**Comment by Ferroric** [comment]
After gaining insight, this is mostly due to new effects of Bik arrows.  Non pf ult will do more damage than a pf ult.  May require some research/testing for said reason.  Addition places to not use pf are telos and aod - if not using full ult anyways.

**Comment by Ferroric** [comment]
Revisit at a later time
