### ISSUE TITLE
Add alternative HM Kerapac P1 rotation

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#2997]
![image](https://user-images.githubusercontent.com/104602266/170160094-f6eef4a1-7d73-44f5-80ff-a7e220a95b36.png)
Link to thread discussing this: https://ptb.discord.com/channels/534508796639182860/537042924026724353/974547663548723260

**Comment by F1shBones** [comment]
I've done that rotation a couple times. It doesn't assume pre-nami. It actually works without it as long as you have Invigorating 4. Nami would actually make it harder to lightning skip P1 if something goes south.

**Comment by F1shBones** [comment]
✅
