### ISSUE TITLE
Rework telos channels

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#3123]
![image](https://user-images.githubusercontent.com/104602266/172274340-1d0f0209-2013-478b-bff8-ee95cd4bc8bd.png)

https://ptb.discord.com/channels/534508796639182860/537042924026724353/982832211545960449
^ thread

**Comment by inferiumRS3** [comment]
doing this

**Comment by inferiumRS3** [comment]
https://github.com/pvme/pvme-guides/pull/3126/
