### ISSUE TITLE
basic guides: add preset breakdowns

### ISSUE THREAD

**Issue by Archken** [pvme/pvme-guides#3289]
- [ ] araxxor 
- [ ] bm
- [ ] ed2
- [ ] ed3
- [x] helwyr
- [ ] kera-hm
- [x] nex
- [ ] raksha
- [ ] telos
- [ ] vorago (x5)

**Comment by Ezeei** [comment]
Helwyr done in #3344

**Comment by Ezeei** [comment]
Nex done in #3352

**Comment by Toosday** [comment]
will get back to this in a few days after updating editor channel related stuff since we can finalize consistent format for preset section in guides there
