### ISSUE TITLE
Update style guide to have preset breakdown

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#3466]
![image](https://user-images.githubusercontent.com/104602266/183537052-93bcc926-036d-4ab8-a8bc-83417722727d.png)

**Comment by Toosday** [comment]
will do this once we finalize format, working on a couple options to get opinions, then can get style guide updated with consistency and add templates and instructions to templates channel as well

**Comment by Toosday** [comment]
Updated all of #style-guide (file attached - [style-guide-update.txt](https://github.com/pvme/pvme-guides/files/9434340/style-guide-update.txt)) except the preset section, I'm just gonna leave it for someone else because I've asked a few times now and haven't gotten any reply.

**Comment by Toosday** [comment]
will work on this tomorrow + day after
