### ISSUE TITLE
update !bolg and !ammo

### ISSUE THREAD

**Issue by Toosday** [pvme/pvme-guides#3477]
![image](https://user-images.githubusercontent.com/108299728/183991316-1db123bd-d85c-4700-9126-a88102dc19eb.png)

**Comment by Archken** [comment]
not sure what is meant by the second point. Im not sure what is meant by "how to use" outside of "just alternate between as needed" and "when is needed" makes more sense to clarify in a boss guide

I can do the !bolg change tomorrow though

**Comment by Archken** [comment]
going to close this issue, gonna scrap second part because cannot implement it in a way that looks appealing / clear, may revisit
