### ISSUE TITLE
Info on only selling gear for direct upgrade

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#3620]
![image](https://user-images.githubusercontent.com/104602266/187818615-d32e5c68-d631-4ec9-a579-472ae1ce7904.png)
Probably better off in upgrade order

**Comment by Archken** [comment]
> Probably better off in upgrade order
![image](https://user-images.githubusercontent.com/77247574/187845661-60eac56c-742d-4ef0-8ff7-f34ac30933e6.png)
nobody reads disclaimers :'c

**Comment by Toosday** [comment]
![image](https://user-images.githubusercontent.com/108299728/187846493-a29948ee-caa2-46cf-a5e9-05847b695373.png)
probably just make it bold and call it a day

**Comment by Ferroric** [comment]
yeah, should be done.  thought I would do to avoid confusion
